#!/usr/bin/env bun
/**
 * Developer script: the only place in the TUI that touches the network.
 *
 * Downloads every tree-sitter grammar and highlight query listed in parser-sources.ts into
 * src/assets/parsers, verifies sha256 against manifest.json, and regenerates NOTICE and
 * src/parsers-config.ts. Run it by hand and commit the result; the app never downloads parsers.
 *
 * Usage:
 *   bun script/fetch-parsers.ts            verify against the manifest, fetch only missing files
 *   bun script/fetch-parsers.ts --update   refetch everything and rewrite the manifest hashes
 */
import { createHash } from "crypto"
import fs from "fs/promises"
import path from "path"
import { QUERIES_LICENSE, parserSources, type ParserSource } from "./parser-sources"

const root = path.resolve(import.meta.dir, "..")
const assetsDir = path.join(root, "src", "assets", "parsers")
const manifestPath = path.join(assetsDir, "manifest.json")
const configPath = path.join(root, "src", "parsers-config.ts")
const noticePath = path.join(assetsDir, "NOTICE")
const update = process.argv.includes("--update")

interface ManifestFile {
  url: string
  sha256: string
  bytes: number
}
type Manifest = Record<string, Record<string, ManifestFile>>

const sha256 = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex")

const download = async (url: string) => {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`)
  return new Uint8Array(await response.arrayBuffer())
}

const readManifest = async (): Promise<Manifest> => {
  const text = await fs.readFile(manifestPath, "utf8").catch(() => undefined)
  return text ? JSON.parse(text) : {}
}

const highlightName = (source: ParserSource, index: number) =>
  source.highlights.length === 1 ? "highlights.scm" : `highlights-${index + 1}.scm`

const wasmName = (source: ParserSource) => path.basename(new URL(source.wasm).pathname)

const files = (source: ParserSource) => [
  { name: wasmName(source), url: source.wasm },
  ...source.highlights.map((url, index) => ({ name: highlightName(source, index), url })),
]

const fetchAll = async () => {
  const previous = await readManifest()
  const manifest: Manifest = {}
  for (const source of parserSources) {
    const dir = path.join(assetsDir, source.filetype)
    await fs.mkdir(dir, { recursive: true })
    manifest[source.filetype] = {}
    for (const file of files(source)) {
      const target = path.join(dir, file.name)
      const expected = previous[source.filetype]?.[file.name]
      const existing = await fs.readFile(target).catch(() => undefined)
      const bytes = existing && !update ? new Uint8Array(existing) : await download(file.url)
      const hash = sha256(bytes)
      if (expected && !update && expected.sha256 !== hash) {
        throw new Error(`sha256 mismatch for ${source.filetype}/${file.name}: expected ${expected.sha256}, got ${hash}`)
      }
      if (!existing || update) await fs.writeFile(target, bytes)
      manifest[source.filetype][file.name] = { url: file.url, sha256: hash, bytes: bytes.byteLength }
      console.log(`${existing && !update ? "ok     " : "fetched"} ${source.filetype}/${file.name} ${hash.slice(0, 12)}`)
    }
  }
  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n")
}

const licenseText = async (repository: string) => {
  for (const name of ["LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING", "COPYING.txt"]) {
    const response = await fetch(`https://raw.githubusercontent.com/${repository}/HEAD/${name}`)
    if (response.ok) return (await response.text()).trim()
  }
  throw new Error(`no license file found in ${repository}`)
}

const writeNotice = async () => {
  const repositories = new Map<string, string>()
  for (const source of parserSources) repositories.set(source.grammar, source.license)
  repositories.set(QUERIES_LICENSE.repository, QUERIES_LICENSE.license)

  const sections: string[] = [
    "Third-party tree-sitter grammars and highlight queries bundled with the CrewCode TUI.",
    "Generated by script/fetch-parsers.ts. Do not edit by hand.",
    "",
    "Summary",
    "-------",
    ...[...repositories].map(([repository, license]) => `${repository}  ${license}`),
  ]
  for (const [repository, license] of repositories) {
    sections.push("", "=".repeat(78), `${repository} (${license})`, "=".repeat(78), "", await licenseText(repository))
  }
  await fs.writeFile(noticePath, sections.join("\n") + "\n")
}

const identifier = (filetype: string, suffix: string) =>
  filetype.replace(/[^a-zA-Z0-9]+(.)/g, (_, char: string) => char.toUpperCase()) + suffix

const writeConfig = async () => {
  const imports: string[] = []
  const entries: string[] = []
  for (const source of parserSources) {
    const dir = `./assets/parsers/${source.filetype}`
    const wasmId = identifier(source.filetype, "Wasm")
    imports.push(`import ${wasmId} from "${dir}/${wasmName(source)}" with { type: "file" }`)
    const highlightIds = source.highlights.map((_, index) => {
      const id = identifier(source.filetype, `Highlights${source.highlights.length === 1 ? "" : index + 1}`)
      imports.push(`import ${id} from "${dir}/${highlightName(source, index)}" with { type: "file" }`)
      return id
    })
    const aliases = source.aliases ? `\n      aliases: ${JSON.stringify(source.aliases)},` : ""
    entries.push(`    {
      filetype: ${JSON.stringify(source.filetype)},${aliases}
      wasm: ${wasmId},
      queries: { highlights: [${highlightIds.join(", ")}] },
    },`)
  }
  const content = `// Generated by script/fetch-parsers.ts. Do not edit by hand.
// Grammars and queries are versioned in src/assets/parsers and embedded in the build, so no parser is ever downloaded at runtime.
/// <reference path="./assets.d.ts" />
${imports.join("\n")}

export default {
  parsers: [
${entries.join("\n")}
  ],
}
`
  await fs.writeFile(configPath, content)
}

await fetchAll()
await writeNotice()
await writeConfig()
const total = Object.values(await readManifest())
  .flatMap((entry) => Object.values(entry))
  .reduce((sum, file) => sum + file.bytes, 0)
console.log(`done: ${(total / 1024 / 1024).toFixed(2)} MiB across ${parserSources.length} parsers`)
