//! The themes that ship with CrewCode, in the same JSON format users write their own in.

/// Name and JSON text of every built-in theme.
pub const BUILTIN: &[(&str, &str)] = &[
    ("aura", include_str!("../themes/aura.json")),
    ("ayu", include_str!("../themes/ayu.json")),
    ("carbonfox", include_str!("../themes/carbonfox.json")),
    ("catppuccin", include_str!("../themes/catppuccin.json")),
    (
        "catppuccin-frappe",
        include_str!("../themes/catppuccin-frappe.json"),
    ),
    (
        "catppuccin-macchiato",
        include_str!("../themes/catppuccin-macchiato.json"),
    ),
    ("cobalt2", include_str!("../themes/cobalt2.json")),
    ("crewcode", include_str!("../themes/crewcode.json")),
    ("cursor", include_str!("../themes/cursor.json")),
    ("dracula", include_str!("../themes/dracula.json")),
    ("everforest", include_str!("../themes/everforest.json")),
    ("flexoki", include_str!("../themes/flexoki.json")),
    ("github", include_str!("../themes/github.json")),
    ("gruvbox", include_str!("../themes/gruvbox.json")),
    ("kanagawa", include_str!("../themes/kanagawa.json")),
    ("lucent-orng", include_str!("../themes/lucent-orng.json")),
    ("material", include_str!("../themes/material.json")),
    ("matrix", include_str!("../themes/matrix.json")),
    ("mercury", include_str!("../themes/mercury.json")),
    ("monokai", include_str!("../themes/monokai.json")),
    ("nightowl", include_str!("../themes/nightowl.json")),
    ("nord", include_str!("../themes/nord.json")),
    ("one-dark", include_str!("../themes/one-dark.json")),
    ("orng", include_str!("../themes/orng.json")),
    ("osaka-jade", include_str!("../themes/osaka-jade.json")),
    ("palenight", include_str!("../themes/palenight.json")),
    ("rosepine", include_str!("../themes/rosepine.json")),
    ("solarized", include_str!("../themes/solarized.json")),
    ("synthwave84", include_str!("../themes/synthwave84.json")),
    ("tokyonight", include_str!("../themes/tokyonight.json")),
    ("vercel", include_str!("../themes/vercel.json")),
    ("vesper", include_str!("../themes/vesper.json")),
    ("zenburn", include_str!("../themes/zenburn.json")),
];
